modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0-only"

[[mixins]]
config="embeddium.mixins.json"

[[mods]]
modId="kalium"
version="${version}"
displayName="Kalium"
logoFile="icon.png"
description='''
Kalium is a performance mod for Minecraft based on the last open-source version of Sodium
'''
credits="embeddedt, NanoLive, CaffeineMC"
authors="embeddedt"

[[dependencies.kalium]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
mandatory = true
versionRange = "[21.1.15,)" #mandatory
ordering = "NONE"
side = "CLIENT"

[[dependencies.kalium]] #optional
modId = "sodium" #mandatory
type = "incompatible" #mandatory
reason="Kalium cannot be used if Sodium is present. If you want to use Kalium you will have to remove Sodium."
versionRange = "[0,)" #mandatory
ordering = "NONE"
side = "CLIENT"
