modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0-only"

[[mixins]]
config="embeddium.mixins.json"

[[mods]]
modId="embeddium"
version="${version}"
displayName="Kalium"
logoFile="icon.png"
description='''
Kalium is a fork of Embeddium, with codes from Celeritas
'''
credits="embeddedt, NanoLive, Bamcane, CaffeineMC"
authors="Bamcane"

[[dependencies.kalium]] #optional
modId = "neoforge" #mandatory
type = "required" #mandatory
mandatory = true
versionRange = "[21.10.12,)" #mandatory
ordering = "NONE"
side = "CLIENT"

[[dependencies.kalium]] #optional
modId = "sodium" #mandatory
type = "incompatible" #mandatory
reason="Kalium cannot be used if Sodium is present. If you want to use Kalium you will have to remove Sodium."
versionRange = "[0,)" #mandatory
ordering = "NONE"
side = "CLIENT"
